### ISSUE TITLE
Unhandled exception executing command 'adminmode' in plugin RPUniverse v0.9

### ISSUE THREAD

**Issue by Fami6Xx** [Fami6Xx/RP-Universe#10]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
	at me.fami6xx.rpuniverse.core.misc.basichandlers.BossBarHandler.updateBossBar(BossBarHandler.java:71) ~[?:?]
	at me.fami6xx.rpuniverse.core.misc.PlayerData.setPlayerMode(PlayerData.java:131) ~[?:?]
	at me.fami6xx.rpuniverse.core.commands.AdminModeCommand.onCommand(AdminModeCommand.java:59) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 21 more

**Comment by Fami6Xx** [comment]
This bug will not be fixed as it was caused by /reload
