### ISSUE TITLE
Cannot invoke "me.fami6xx.rpuniverse.core.jobs.Position.getName()" because the return value of "me.fami6xx.rpuniverse.core.jobs.Job.getPlayerPosition(java.util.UUID)" is null

### ISSUE THREAD

**Issue by Fami6Xx** [Fami6Xx/RP-Universe#11]
java.lang.NullPointerException: Cannot invoke "me.fami6xx.rpuniverse.core.jobs.Position.getName()" because the return value of "me.fami6xx.rpuniverse.core.jobs.Job.getPlayerPosition(java.util.UUID)" is null
	at me.fami6xx.rpuniverse.core.jobs.commands.jobs.menus.JobPlayerMenu.setMenuItems(JobPlayerMenu.java:82) ~[?:?]
	at me.fami6xx.rpuniverse.core.menuapi.types.Menu$1.run(Menu.java:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by Fami6Xx** [comment]
This bug won't be fixed as it was caused by using /reload
