### ISSUE TITLE
IllegalArgumentException: Health must be between 0 and 20.0, but was 21.0

### ISSUE THREAD

**Issue by Fami6Xx** [Fami6Xx/RP-Universe#9]
[22:50:04] [Server thread/ERROR]: Could not pass event PlayerItemConsumeEvent to RPUniverse v0.9
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 21.0. (attribute base value: 20.0, player: fokman)
	at org.bukkit.craftbukkit.v1_18_R2.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:110) ~[paper-1.18.2.jar:git-Paper-388]
	at me.fami6xx.rpuniverse.core.basicneeds.events.FoodTrackerListener.onPlayerConsume(FoodTrackerListener.java:36) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor167.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:3818) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1709) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3680) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2288) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3661) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2878) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:314) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1623) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by Fami6Xx** [comment]
Fixed
